config/routes.rb
Rails.application.routes.draw do
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy' 
 resources :authors 
  resources :tags
 
get '/authors/:author_id/quotes' =>'quotes#index', as: 'author_quotes'
post '/authors/:author_id/quotes' =>'quotes#create', as: 'create_author_quotes'
get '/authors/:author_id/quotes/new' =>'quotes#new', as: 'new_author_quotes'
get '/authors/:author_id/quotes/:id/edit' =>'quotes#edit', as: 'edit_author_quotes'
get '/authors/:author_id/quotes/:id' =>'quotes#show', as: 'show_author_quotes'
patch '/authors/:author_id/quotes/:id' =>'quotes#update', as: 'update_author_quotes'
delete '/authors/:author_id/quotes/:id' =>'quotes#delete', as: 'delete_author_quotes'

get '/users' =>'users#index', as: 'users'
post '/users' =>'users#create', as: 'create_users'
get '/users/signup' =>'users#new', as: 'new_users'
get '/users/:id' =>'users#show', as: 'show_users'
get '/users/:id/edit' =>'users#edit', as: 'edit_users'
patch '/users/:id' =>'users#update', as: 'update_users'
delete '/users/:id' =>'users#delete', as: 'delete_users'
get '/login' => 'users#login', as: 'login_users'
post '/users/authenticate' => 'users#auth', as:'auth_users'

post '/tags' =>'tags#create', as: 'create_tag'
patch '/tags/:id' =>'tags#update', as: 'update_tag'
get '/tags' =>'tags#index', as: 'index_tag'
delete '/tags.:id' =>'tags#delete', as: 'delete_tag'


root 'quotes#randomizer' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
belongs_to :author
has_many :quote_tags , dependent: :destroy
has_many :tags, through: :quote_tags , dependent: :destroy
validates :quote, presence: true, uniqueness:true, length: {minimum:10, maximum:200}
validates :author_id, presence: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :logged_in_user, only: [:randomizer,:new,:edit,:update]
  before_action :admin_user, only: [:delete]
  def randomizer
    @author_all = Author.all
    def select_random_author 
      @author_sample = @author_all.sample(1)
      @author_name = @author_sample[0].author_name
      @quotes_of_author =  @author_sample[0].quotes
      while @quotes_of_author.length == 0 
        select_random_author
      end
    end
      select_random_author
      @quote_sample = @author_sample[0].quotes.sample(1)
      @quote_print = @quote_sample[0].quote
  end


  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @author = Author.find(params[:author_id])
    @quote = @author.quotes.build
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.author_id = params[:author_id]
    @quote.tag_ids.map! {|x| x.to_i }
    #  byebug
    if @quote.save
      redirect_to author_path(@quote.author)
    else
      byebug
      render 'new'
    end
  end

  def edit
  # For some reason, the "author_id" and "id" have their values switched
    @quote = Quote.find(params[:id])
  end

  def update
  @quote = Quote.find(params[:id])

  if @quote.update(params.require(:quote).permit(:quote, :author_id,tag_ids: []))
    redirect_to author_path(@quote.author)
  else
    render 'edit'
  end
  end

  def delete
   @quote = Quote.find(params[:id])
   @quote.destroy
   redirect_to author_path
  end
   
  private
  def quote_params
    params.require(:quote).permit(:quote, :author_id, tag_ids: [])
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/edit.erb
<body class ="show-body-author">

  <header class = "show-header-author">
    <span class ="title">My Desk <span>
  </header>

  <div class = 'container-quotes-edit'>
    <div class = "list-title-add-edit">
      <span class = "title-label-edit">Edit Quotes</span> 
    </div>

    <%= form_with model: @quote, url: update_author_quotes_path() ,local: true do |form| %>

      <div class ='form-edit'>
        <div class = 'edit-body'>
          <span class= "label-edit-quote"> Quote: </span>
        <%= form.text_area :quote, class: 'input-quote' %><br>
        
        <span class= "label-edit-quote"> Author: </span>
        <%= form.select :author_id, Author.all.collect { |p| [ p.author_name, p.id ] }, include_blank: "-select author-",class: "dropdown-select" %>

         <div class ="form-tags">
          <%= form.collection_check_boxes :tag_ids,  Tag.all, :id, :tag_name, include_hidden: false do |b| %>
          <div class="collection-check-box">
            <%= b.check_box %>
            <%= b.label %>
          </div>
          <% end %>
        </div>  
      </div>

      <div class="submit">
      <%= form.submit "Save Quote", class: "submit-edit" %>
      </div>
    <%end%>
  </div>
</body>

app/views/quotes/edit.html.erb
<body class ="show-body-author">

  <header class = "show-header-author">
    <span class ="title">My Desk <span>
  </header>

  <div class = 'container-quotes-edit'>
    <div class = "list-title-add-edit">
      <span class = "title-label-edit">Edit Quotes</span> 
    </div>

    <%= form_with model: @quote, url: update_author_quotes_path() ,local: true do |form| %>

      <div class ='form-edit'>
        <div class = 'edit-body'>
          <span class= "label-edit-quote"> Quote: </span>
        <%= form.text_area :quote, class: 'input-quote' %><br>
        
        <span class= "label-edit-quote"> Author: </span>
        <%= form.select :author_id, Author.all.collect { |p| [ p.author_name, p.id ] }, include_blank: "-select author-",class: "dropdown-select" %>
      </div>

      <div class="submit">
      <%= form.submit "Save Quote", class: "submit-edit" %>
      </div>
    <%end%>
  </div>
</body>

app/views/quotes/new.erb
<body class ="show-body-author">

  <header class = "show-header-author">
  <span class ="title">My Desk <span>
  </header>

  <div class = 'container-quotes-edit'>
      <div class = "list-title-add-edit">
        <span class = "title-label-edit">Edit Quotes</span> 
      </div>

    <%= form_with model:@quote, :url => {:controller => 'quotes', :action => 'create'} do |f| %>

    <div class ="form-body">

      <div class ="form-parts">
          <span class ="label-edit-quote">Quote:</span>
          <%= f.text_area :quote, class: 'input-quote'%>
      </div>

      <div class ="form-tags">
        <%= f.collection_check_boxes :tag_ids,  Tag.all, :id, :tag_name, include_hidden: false do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
        <% end %>
      </div>

      <div class="submit">
      <%=f.submit "Add Quote", class:"submit-edit" %>
      </div>
    </div>
  <% end %>
  </div>

<%= link_to 'Back',root_path %>
</body>

app/views/quotes/new.html.erb
<body class ="show-body-author">

  <header class = "show-header-author">
  <span class ="title">My Desk <span>
  </header>

  <div class = 'container-quotes-edit'>
      <div class = "list-title-add-edit">
        <span class = "title-label-edit">Edit Quotes</span> 
      </div>

    <%= form_for(:quote, :url => {:controller => 'quotes', :action => 'create'}) do |f| %>

    <div class ="form-body">

      <div class ="form-parts">
          <span class ="label-edit-quote">Quote:</span>
          <%= f.text_area :quote, class: 'input-quote'%>
      </div>

      <div class="submit">
      <%=f.submit "Add Quote", class:"submit-edit" %>
      </div>
    </div>
  <% end %>
  </div>

<%= link_to 'Back',root_path %>
</body>

app/views/quotes/randomizer.html.erb
<body class = "body-randomizer">
  <div class="container-1">
    <div class = "time">
      TIME
    </div>
    <div class ="name">
      Good morning, Jose!
    </div>
    <div class = "task">
        <div class = "task-label">
        What is your main task today?
        </div>
        <div class = "task-list">
        ______________________________
        <div>
    </div>
    <div class = "quote">
    "<%=  @quote_print %>" - <%= @author_name %>
    </div>
    </div>

    <div>
  
  </div>

<body>