config/routes.rb
Rails.application.routes.draw do
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy' 
 resources :authors 
  resources :tags
 
get '/authors/:author_id/quotes' =>'quotes#index', as: 'author_quotes'
post '/authors/:author_id/quotes' =>'quotes#create', as: 'create_author_quotes'
get '/authors/:author_id/quotes/new' =>'quotes#new', as: 'new_author_quotes'
get '/authors/:author_id/quotes/:id/edit' =>'quotes#edit', as: 'edit_author_quotes'
get '/authors/:author_id/quotes/:id' =>'quotes#show', as: 'show_author_quotes'
patch '/authors/:author_id/quotes/:id' =>'quotes#update', as: 'update_author_quotes'
delete '/authors/:author_id/quotes/:id' =>'quotes#delete', as: 'delete_author_quotes'

get '/users' =>'users#index', as: 'users'
post '/users' =>'users#create', as: 'create_users'
get '/users/signup' =>'users#new', as: 'new_users'
get '/users/:id' =>'users#show', as: 'show_users'
get '/users/:id/edit' =>'users#edit', as: 'edit_users'
patch '/users/:id' =>'users#update', as: 'update_users'
delete '/users/:id' =>'users#delete', as: 'delete_users'
get '/login' => 'users#login', as: 'login_users'
post '/users/authenticate' => 'users#auth', as:'auth_users'

post '/tags' =>'tags#create', as: 'create_tag'
patch '/tags/:id' =>'tags#update', as: 'update_tag'
get '/tags' =>'tags#index', as: 'index_tag'
delete '/tags.:id' =>'tags#delete', as: 'delete_tag'


root 'quotes#randomizer' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :quotes,  dependent: :destroy
  validates :author_name, presence: true, uniqueness: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :logged_in_user, only: [:edit,:update]
  before_action :admin_user, only: [:delete]
  def new
    
  end
  
  def create
    @author = Author.new(author_params)
    @author.save
    redirect_to @author
  end

  def show
    @author = Author.find(params[:id])
    @quotes = @author.quotes
  end

  def index
    @authors = Author.all
  end

  def  edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to authors_path(@author)
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.quotes.delete_all 
    @author.destroy
    redirect_to authors_path
  end

  private

  def author_params
   params.require(:author).permit(:author_name)
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<body class ="show-body-author">

	<header class = "show-header-author">
	<span class ="title">My Desk <span>
	</header>


  
  <div class = 'container-quotes-edit'>
    <div class = "author-title">
      New Author
    </div>
      <%= form_with(model: @author, :url => {:controller => 'authors', :action => 'update'}) do |f| %>
      <div class = "form-parts">
      <span class ="label-edit-quote">Author:</span>
        <%= f.text_field :author_name, class: 'input-quote' %>
      </div>

      <div class = "submit">
      <%= f.submit :"Save", class:"submit-edit" %>
    </div>
    <%end%>
</div>

</body>

app/views/authors/index.html.erb
<body class ="show-body-author">
	<header class = "show-header-author">
	<span class ="title">My Desk <span>
	</header>

  <div class ="container-show-author-index">
    <h1 class ="list-author-title"> List of all Authors </h1>

<table>
<% @authors.each do |author| %>
  <tr>
    <td><%=author.author_name%></td>
    <td><%= link_to 'Show Quotes of Author', author_path(author), class:"quotes-author  " %></td>
    <td>
      <%= link_to edit_author_path(author), class: 'option-quote option-quote-edit' do %>
      <i class="far fa-edit"></i> 
      <%end%>
    </td>
    <td><%= link_to author_path(author) ,method: :delete,data: { confirm: 'Are you sure?' } ,class: 'option-quote option-quote-delete' do%>
      <i class="far fa-trash-alt"></i>
      <%end%>
    </td>
 </tr>
<%end%>
</table>
</div>
</body>

app/views/authors/new.html.erb
<h1> Create New User </h1>

<%= form_for :author , url: authors_path do |f| %>
  <p>
    <%= f.label :"Author's Name:" %>
    <%= f.text_field :author_name %>
  </p>

  <p>
  <%= f.submit :"Create Author" %>
</p>
<%end%>

app/views/authors/show.html.erb
<body class ="show-body-author">

	<header class = "show-header-author">
	<span class ="title">My Desk <span>
	</header>


	<div class ="container-show-author">
		<div class="body-top">
			<div class = "author-title">
				Author:
			</div>

			<div class="author-name">			
				<%= @author.author_name %>
			</div>			

			<div class="link-to-add">
			<i class="fas fa-plus fa-xs"></i>
				<%= link_to "Add Quotes",  new_author_quotes_path(@author), class: "link-to-add-inside" %>
			</div>	
		</div>

	<div class="body-bottom">
		<div class = "author-title">
			Quotes:
		</div>

		<table class ="quote-list">
		<% @quotes.each do |quote| %>

			<tr class ="quotes">
				<td>
					<i class="fas fa-angle-right fa-1x arrow-icon"></i>
					<%= quote.quote %>
				</td>	 
				<td>
					<%= link_to edit_author_quotes_path(quote), class: 'option-quote option-quote-edit' do %>
					<i class="far fa-edit"></i> 
					<%end%>
				</td>
				<td>
					<%= link_to delete_author_quotes_path(quote) ,method: :delete, class: 'option-quote option-quote-delete' do%>
					<i class="far fa-trash-alt"></i>
					<%end%>
				</td>
			</tr>
		<%end%>
		</table>
	</div>

</body>