config/routes.rb
Rails.application.routes.draw do
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy' 
 resources :authors 
  resources :tags
 
get '/authors/:author_id/quotes' =>'quotes#index', as: 'author_quotes'
post '/authors/:author_id/quotes' =>'quotes#create', as: 'create_author_quotes'
get '/authors/:author_id/quotes/new' =>'quotes#new', as: 'new_author_quotes'
get '/authors/:author_id/quotes/:id/edit' =>'quotes#edit', as: 'edit_author_quotes'
get '/authors/:author_id/quotes/:id' =>'quotes#show', as: 'show_author_quotes'
patch '/authors/:author_id/quotes/:id' =>'quotes#update', as: 'update_author_quotes'
delete '/authors/:author_id/quotes/:id' =>'quotes#delete', as: 'delete_author_quotes'

get '/users' =>'users#index', as: 'users'
post '/users' =>'users#create', as: 'create_users'
get '/users/signup' =>'users#new', as: 'new_users'
get '/users/:id' =>'users#show', as: 'show_users'
get '/users/:id/edit' =>'users#edit', as: 'edit_users'
patch '/users/:id' =>'users#update', as: 'update_users'
delete '/users/:id' =>'users#delete', as: 'delete_users'
get '/login' => 'users#login', as: 'login_users'
post '/users/authenticate' => 'users#auth', as:'auth_users'

post '/tags' =>'tags#create', as: 'create_tag'
patch '/tags/:id' =>'tags#update', as: 'update_tag'
get '/tags' =>'tags#index', as: 'index_tag'
delete '/tags.:id' =>'tags#delete', as: 'delete_tag'


root 'quotes#randomizer' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: {minimum:3, maximum:25}
  validates :email, presence: true, uniqueness: true, length: {minimum:3, maximum:125}
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show,:edit,:update]
  # before_action :admin_user, only: [:delete]
  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
   if @user.save
    flash[:alert] = "User created."
    redirect_to users_path
   else
     render 'new'
   end
  end

  def login
    
  end

  def show
    @user = User.find(session[:user_id])
  end

  def index 
    current_user
    @user = User.all
    @inactive_users = @user.select do |user|
      user.id != session[:user_id]
    end
    # @checker = (session[:user_id] == @user.id)
  end

  def  edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update(params_user)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find_by(params[:id])
    @user.destroy
    log_out
    redirect_to users_path
  end

  private
  def params_user
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body class ="show-body">

<header class = "show-header">
 <span class ="title">My Desk <span>
</header>

<div class ="container">
<div class = "page-title">
Edit Info 
</div>

  <%= form_with(model: @user, :url => {:controller => 'users', :action => 'update'}, class: "form-field") do |f| %>
    <div class ="body-form">
    <strong class ="label">Username: </strong>
    <%= f.text_field :username, class:"text-field"%> 
    </div>   
    
    <div class ="body-form">
    <strong class ="label">Email: </strong>
    <%= f.text_field :email, class:"text-field"%> 
    </div>  
    <div class ="body-form">
    <strong class ="label">Password: </strong>
    <%= f.text_field :password, class:"text-field"%> 
    </div>  
    
    
    <%= f.submit :Save, class: "submit-btn" %>
    
  <% end %>


  <div class ="buttons">
  <%= link_to show_users_path(@user), class:"edit-btn btn" do%>
    <i class="fas fa-caret-left arrow fa-2x"></i> <span class ='label-btn'>Back</span>
  <%end%>

  </div>

  </body>

app/views/users/index.html.erb
<body class ="show-body">

<header class = "show-header">
 <span class ="title">My Desk <span>
</header>

<div class ="container-index">
<div class = "page-title">
List of Users
</div>


<% if (session[:user_id] == nil) %>
  <%= link_to 'Log in User', login_path, class: "login-link-index"%>
<%end%>


<% if (session[:user_id] != nil) %>
<div class ="active-user">

<div class = "active-user-title">
Active User
</div>

 <div class ="body-active-user"> 
    <div class="container-info">
      <div class ="body-info-index">
        <strong class ="label-index">Username: </strong>
        <span class ="info-index"><%= @current_user.username%> </span>
      </div>

      <div class ="body-info-index">
        <strong class ="label-index">Email: </strong>
        <span class ="info-index"><%= @current_user.email%> </span>
      </div>
    </div>

    <div class="options-index">
      <div class="option">
        <%= link_to 'Show User Data', show_users_path(@current_user), class:"links"%>
      </div>

      <div class="option">
        <%= link_to 'Edit', edit_users_path(@current_user),class:"links edit-link"%>
        <%= link_to 'delete', delete_users_path(@current_user), method: :delete, data: { confirm: 'Are you sure?' },class:"links delete-link"%>
      </div>
    </div>
  </div>

</div>
<%end%>
<table class = "list-of-users">
  <thead>
    <th>Username</th>
    <th>Email</th>
  </thead>
<% @inactive_users.each do |user| %>
   <tr>
   <td><%= user.username %></td>
   <td><%= user.email %></td>
  
   <%end%>
</table>

</div>

</body>

app/views/users/new.html.erb
<body class= "body-new">

  <div class ="container">

    <div class ="title-signup"> Sign up </div>
    <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    
      <div class ="form-parts">
        <span class ="form-labels">Username:</span>
        <%= f.text_field :username, class: "input-fields" %>
      </div>

      <div class ="form-parts">
        <span class ="form-labels">Email:</span>
        <%= f.text_field :email, class: "input-fields" %>
      </div>

      <div class ="form-parts">
        <span class ="form-labels">Password:</span>
        <%= f.password_field :password, class: "input-fields" %>
      </div>

      <div class ="form-button">
      <%= f.submit "Sign up", class: "button" %>
      </div>
      
    <% end %>
    <% if @user.errors.any? %>
      <ul class="Signup_Errors">
      <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
      <% end %>
      </ul>
    <% end %>

    <span class ="signup">
      Already have an account?
      <%= link_to 'Login here', login_users_path, class: "login-link" %>
    </span>
    
  </div>
 </body> 

app/views/users/show.html.erb
<body class ="show-body">

  <header class = "show-header">
   <span class ="title">My Desk <span>
  </header>
 
  <div class ="container">

    <div class = "page-title">
    User Data
    </div>

    <div class ="body-info">
    <strong class ="label">Username: </strong>
    <span class ="info"><%= @user.username%> </span>
    </div>

    <div class ="body-info">
    <strong class ="label">Email: </strong>
    <span  class ="info"><%= @user.email%> </span>
    </div>

    <div class ="buttons">
    <%= link_to edit_users_path(@user), class:"edit-btn btn" do%>
      <i class="fas fa-caret-left arrow fa-2x"></i> <span class ='label-btn'>Edit</span>
    <%end%>
    <%= link_to delete_users_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-btn btn" do%>
      <span class ='label-btn'>Delete</span>
    <%end%>
    <%= link_to logout_path, method: :delete,class: "logout-btn btn" do%>
      <span class ='label-btn'>Log out</span><i class="fas fa-caret-right arrow fa-2x"></i>
      <%end%>
    </div>

    <div class="link-to-users">
    <%= link_to 'List of Users', users_path, class:'link-btn'%>
    </div>
  </div>

</body>