config/routes.rb
Rails.application.routes.draw do
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy' 
 resources :authors 
  resources :tags
 
get '/authors/:author_id/quotes' =>'quotes#index', as: 'author_quotes'
post '/authors/:author_id/quotes' =>'quotes#create', as: 'create_author_quotes'
get '/authors/:author_id/quotes/new' =>'quotes#new', as: 'new_author_quotes'
get '/authors/:author_id/quotes/:id/edit' =>'quotes#edit', as: 'edit_author_quotes'
get '/authors/:author_id/quotes/:id' =>'quotes#show', as: 'show_author_quotes'
patch '/authors/:author_id/quotes/:id' =>'quotes#update', as: 'update_author_quotes'
delete '/authors/:author_id/quotes/:id' =>'quotes#delete', as: 'delete_author_quotes'

get '/users' =>'users#index', as: 'users'
post '/users' =>'users#create', as: 'create_users'
get '/users/signup' =>'users#new', as: 'new_users'
get '/users/:id' =>'users#show', as: 'show_users'
get '/users/:id/edit' =>'users#edit', as: 'edit_users'
patch '/users/:id' =>'users#update', as: 'update_users'
delete '/users/:id' =>'users#delete', as: 'delete_users'
get '/login' => 'users#login', as: 'login_users'
post '/users/authenticate' => 'users#auth', as:'auth_users'

post '/tags' =>'tags#create', as: 'create_tag'
patch '/tags/:id' =>'tags#update', as: 'update_tag'
get '/tags' =>'tags#index', as: 'index_tag'
delete '/tags.:id' =>'tags#delete', as: 'delete_tag'


root 'quotes#randomizer' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :quote_tags
has_many :quotes, through: :quote_tags
validates :tag_name, presence: true, uniqueness: true, length: {minimum:2}
end
 

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tags_params)
    redirect_to tags_path
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tags_params)
    redirect_to tags_path
    else
      render 'edit'
    end
  end

  def delete
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to index_tag_path
  end

  private
  def tags_params
    params.require(:tag).permit(:tag_name, quote_id: [])
  end

end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/edit.html.erb
<body class ="show-body-author">

  <header class = "show-header-author">
    <span class ="title">My Desk <span>
  </header>

  <div class ="container">

    <div class ="title-signup"> Edit Tag </div>
      <%= form_with(model: @tag, :url => {:controller => 'tags', :action => 'update'}) do |f| %>
      
        <div class ="form-parts">
          <span class ="form-labels">Tag:</span>
          <%= f.text_field :tag_name, class: "input-fields" %>
        </div>

        <div class ="form-button">
          <%= f.submit "Save", class: "button" %>
        </div>
        
      <% end %>

  </div>
</body> 

app/views/tags/index.erb
<body class ="show-body-author">

  <header class = "show-header-author">
    <span class ="title">My Desk <span>
  </header>

  <div class ="container">
    <h1> Tags </h1>
    <div class ="container-tag">
    	
      <% @tags.each do |tag| %>
        <div class='tags'>
          <%= link_to tag_path(tag), class: 'tag' do%>
					<%= tag.tag_name %>
		    	<%end%>
         </div>
      <%end%>
    </div>
  </div>
</body> 

app/views/tags/new.html.erb
<body class ="show-body-author">

<header class = "show-header-author">
<span class ="title">My Desk <span>
</header>

<div class ="container">

  <div class ="title-signup"> New Tag </div>
  <%= form_for(:tag, :url => {:controller => 'tags', :action => 'create'}) do |f| %>
  
    <div class ="form-parts">
      <span class ="form-labels">Tag:</span>
      <%= f.text_field :tag_name, class: "input-fields" %>
    </div>

    <div class ="form-button">
    <%= f.submit "Sign up", class: "button" %>
    </div>
    
  <% end %>
    
  
</div>
</body> 

app/views/tags/show.erb
<body class ="show-body-author">

<header class = "show-header-author">
<span class ="title">My Desk <span>
</header>

<div class ="container">

  <div class ="title-signup"> Tag  </div>
  
    <div class ="form-parts">
      <span class = "tag"><%= @tag.tag_name%></span>
    </div>

    <div class ="form-button">
      <span class= 'tag-link'>
      <%= link_to 'Edit', edit_tag_path(@tag), class:"links"%>
      </span>
      <span  class= 'tag-link'>
      <%= link_to 'Delete', delete_tag_path(@tag), class:"links", method: :delete %>
      </span>
    </div>
    
    
  
</div>
</body> 